### ISSUE TITLE
Enhance non-article post tracking

### ISSUE THREAD

**Issue by hoppy-kamper** [PicoNetworks/wordpress-plugin#142]
We currently try to determine what "type" a post is through Article.resource_ref. The resource ref works fine as a foreign-key for the Wordpress site, but is not trustworthy to determine the `post-type` of an article or page.

- [ ] Add a `post_type` to the Articles table. These should be of type `post`(article, `page`, `homepage`, `index` etc...
- [ ] Treat all posts (all pages in wordpress) the same, sending across catagories/tags if available. These should be stored in the Pico database.
- [ ] Test our whitelisting/blacklisting feature with the properly categorized post types. The implementation should already be working.

**Comment by hoppy-kamper** [comment]
@nychen Note that Impact Alpha's homepage will continue to be broken until this is fixed
